export const WORKSPACE_MODULES = {
  PROJECTS: "PROJECTS",
  TICKETS: "TICKETS",
};

export const WORKSPACE_SECTIONS = {
  MY_ASSIGNED_PROJECTS: "MY_ASSIGNED_PROJECTS",
  CREATE_PROJECT: "CREATE_PROJECT",
  RAISE_TICKET: "RAISE_TICKET",
  MY_RAISED_TICKETS: "MY_RAISED_TICKETS",
  MY_ASSIGNED_TICKETS: "MY_ASSIGNED_TICKETS",
};